# amazon props
cloud.aws.region.auto=false
cloud.aws.region.static=eu-central-1
cloud.aws.credentials.accessKey=AKIA4MCKY6KRK3NHYYOL
cloud.aws.credentials.secretKey=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
cloud.aws.credentials.instanceProfile=true
cloud.aws.credentials.useDefaultAwsCredentialsChain=true
cloud.aws.stack.auto=false

# max size of uploading files
spring.codec.max-in-memory-size=5MB

# H2 SETTINGS:
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
