
# max size of uploading files
spring.codec.max-in-memory-size=5MB

# DB SETTINGS
spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#JWT SETTINGS:
jwt.secret.word=${JWT_SECRET}
jwt.expiration.time=1
jwt.prefix=Bearer_

cors.origin.network=${ALLOWED_ORIGIN}

images.api.key=${API_KEY}
error.image.url=${ERR_IMG_URL}

#mail settings:
spring.mail.host=smtp.mail.yahoo.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
confirm.reg.message=${CONFIRM_MESSAGE}
